### ISSUE TITLE
bot crashing by Error

### ISSUE THREAD

**Issue by Z0MBlI** [FKLC/WhatsAppToDiscord#101]
{"level":30,"time":1662344603694,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Starting"}
{"level":30,"time":1662344604060,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Update checked."}
{"level":30,"time":1662344604178,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Initialized database."}
{"level":30,"time":1662344604179,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Loaded settings."}
{"level":30,"time":1662344604180,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Loaded contacts."}
{"level":30,"time":1662344604182,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Loaded chats."}
{"level":30,"time":1662344604861,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Discord client started."}
{"level":30,"time":1662344605508,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Repaired channels."}
{"level":30,"time":1662344605696,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"WhatsApp client started."}
{"level":30,"time":1662344605767,"pid":12472,"hostname":"DESKTOP-OLBVT75","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"xhB16ZWnNBRqPQat8plxp0b+/wlWpqzzFqNJUh2KMTQ="}},"msg":"connected to WA Web"}
{"level":30,"time":1662344605807,"pid":12472,"hostname":"DESKTOP-OLBVT75","node":{"username":"4915152218680","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2230,"tertiary":15},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":26},"msg":"logging in..."}
{"level":30,"time":1662344606285,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"23 pre-keys found on server"}
{"level":30,"time":1662344606318,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"opened connection to WA"}
{"level":30,"time":1662344606468,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"handled 0 offline messages/notifications"}
{"level":30,"time":1662352513448,"pid":12472,"hostname":"DESKTOP-OLBVT75","trace":"Error: Connection Terminated\n    at WebSocket.<anonymous> (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:350:30)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emitClose (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\ws\\lib\\websocket.js:258:10)\n    at Receiver.receiverOnFinish (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\ws\\lib\\websocket.js:1167:20)\n    at Receiver.emit (node:events:527:28)\n    at finish (node:internal/streams/writable:746:10)\n    at node:internal/streams/writable:724:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","msg":"connection errored"}
{"level":50,"time":1662352513448,"pid":12472,"hostname":"DESKTOP-OLBVT75","err":{"type":"Error","message":"Connection Terminated","stack":"Error: Connection Terminated\n    at WebSocket.<anonymous> (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:350:30)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emitClose (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\ws\\lib\\websocket.js:258:10)\n    at Receiver.receiverOnFinish (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\ws\\lib\\websocket.js:1167:20)\n    at Receiver.emit (node:events:527:28)\n    at finish (node:internal/streams/writable:746:10)\n    at node:internal/streams/writable:724:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated"},"headers":{}}},"msg":"Connection Terminated"}
{"level":50,"time":1662352535520,"pid":12472,"hostname":"DESKTOP-OLBVT75","err":{"type":"HTTPError","message":"request to https://discord.com/api/v9/channels/989943871779795034/messages failed, reason: getaddrinfo ENOTFOUND discord.com","stack":"FetchError: request to https://discord.com/api/v9/channels/989943871779795034/messages failed, reason: getaddrinfo ENOTFOUND discord.com\n    at RequestHandler.execute (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\discord.js\\src\\rest\\RequestHandler.js:201:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async RequestHandler.push (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\discord.js\\src\\rest\\RequestHandler.js:51:14)\n    at async TextChannel.send (C:\\snapshot\\WhatsAppToDiscord\\node_modules\\discord.js\\src\\structures\\interfaces\\TextBasedChannel.js:176:15)\n    at async EventEmitter.<anonymous> (C:\\snapshot\\WhatsAppToDiscord\\src\\whatsapp_manager.js:30:9)","name":"FetchError","code":500,"method":"post","path":"/channels/989943871779795034/messages","requestData":{"json":{"content":"WhatsApp connection failed! Trying to reconnect! Retry #1","tts":false},"files":[]}},"msg":"request to https://discord.com/api/v9/channels/989943871779795034/messages failed, reason: getaddrinfo ENOTFOUND discord.com"}
{"level":30,"time":1662352535520,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Exiting!"}
{"level":30,"time":1662352535534,"pid":12472,"hostname":"DESKTOP-OLBVT75","msg":"Exiting!"}

**Comment by FKLC** [comment]
This is more of a DNS issue, and I can't really reproduce the issue on my end. Are you able to interact with discord? Because, the problem is the program can't find the IP address of discord.com.

**Comment by Z0MBlI** [comment]
ok, it's only happened to me once so far. Haven't had any more problems so far. Thanks for the great work. keep it up

**Comment by FKLC** [comment]
I see. Closing the issue then.
