### ISSUE TITLE
ARM64 - RASP4 - error with JAVA and ELF

### ISSUE THREAD

**Issue by klap50** [FKLC/WhatsAppToDiscord#168]
UBUNTU SERVER 22.04 LTS
RASPY 4 8 GB RAM - ARM64 - 

```
```
klap@rammstein:~/bot_dicord/WhatsAppToDiscord$ ./WA2DC-Linux-arm64
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module '/snapshot/WhatsAppToDiscord/out.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.5.0
```
klap@rammstein:~/bot_dicord/WhatsAppToDiscord$ node WA2DC-Linux-arm64 
/home/klap/bot_dicord/WhatsAppToDiscord/WA2DC-Linux-arm64:1
ELF
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by FKLC** [comment]
Hmm, I don't know what might cause this. As a temporary solution (until next release), you can run using the source code, just clone the repo, `npm install`, then run `npm run start`

**Comment by weskerty** [comment]
same Debian12 arm64
