### ISSUE TITLE
panic: HTTP 413 Request Entity Too Large

### ISSUE THREAD

**Issue by seffs** [FKLC/WhatsAppToDiscord#23]
Hi there,

This is a new kind of error that I keep on receiving since yesterday. Here the log

```
2020-12-24T13:12:12.436624+00:00 app[worker.1]: [heroku-exec] Starting
2020-12-24T13:12:51.371350+00:00 app[worker.1]: Bot is now running. Press CTRL-C to exit.
2020-12-24T13:13:28.883370+00:00 app[worker.1]: error processing data: received invalid data
2020-12-24T13:13:32.690223+00:00 app[worker.1]: error processing data: received invalid data
2020-12-24T13:13:34.612351+00:00 app[worker.1]: error processing data: received invalid data
2020-12-24T13:50:43.751748+00:00 app[worker.1]: panic: HTTP 413 Request Entity Too Large, {"message": "Request entity too large", "code": 40005}
2020-12-24T13:50:43.751760+00:00 app[worker.1]: 
2020-12-24T13:50:43.751799+00:00 app[worker.1]: goroutine 1403 [running]:
2020-12-24T13:50:43.751810+00:00 app[worker.1]: main.handleMediaMessage(0xc002b505a0, 0x20, 0xc002b504e0, 0x1d, 0x0, 0x0, 0x0, 0x5fe49cb1, 0x0, 0x0, ...)
2020-12-24T13:50:43.751811+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:450 +0x6fc
2020-12-24T13:50:43.751839+00:00 app[worker.1]: main.waHandler.HandleVideoMessage(0xc002b505a0, 0x20, 0xc002b504e0, 0x1d, 0x0, 0x0, 0x0, 0x5fe49cb1, 0x0, 0x0, ...)
2020-12-24T13:50:43.751855+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:475 +0x1da
2020-12-24T13:50:43.751871+00:00 app[worker.1]: created by github.com/Rhymen/go-whatsapp.(*Conn).handleWithCustomHandlers
2020-12-24T13:50:43.751887+00:00 app[worker.1]: /tmp/codon/tmp/cache/go-path/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.0/handler.go:222 +0x1068
2020-12-24T13:50:43.806782+00:00 heroku[worker.1]: Process exited with status 2
2020-12-24T13:50:43.845819+00:00 heroku[worker.1]: State changed from up to crashed
2020-12-24T13:50:43.849375+00:00 heroku[worker.1]: State changed from crashed to starting
2020-12-24T13:50:44.961847+00:00 heroku[worker.1]: Starting process with command `bin/WhatsAppToDiscord`
2020-12-24T13:50:45.660477+00:00 heroku[worker.1]: State changed from starting to up
2020-12-24T13:50:48.829393+00:00 app[worker.1]: [heroku-exec] Starting
2020-12-24T13:55:52.568543+00:00 app[worker.1]: panic: interface conversion: interface {} is nil, not string
2020-12-24T13:55:52.575503+00:00 app[worker.1]: 
2020-12-24T13:55:52.585066+00:00 app[worker.1]: goroutine 1 [running]:
2020-12-24T13:55:52.585796+00:00 app[worker.1]: github.com/Rhymen/go-whatsapp.(*Conn).Login(0xc000448ee0, 0xc000225ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-12-24T13:55:52.585994+00:00 app[worker.1]: /tmp/codon/tmp/cache/go-path/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.0/session.go:234 +0x23cf
2020-12-24T13:55:52.586103+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.586284+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:344 +0x11c
2020-12-24T13:55:52.586412+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.586615+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.586698+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.586927+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.586992+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.587228+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.587327+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.587491+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.587622+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.587843+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.587905+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.588127+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.588197+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.588379+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.588462+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.588647+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.588729+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.588919+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.589003+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.589190+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.589274+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.589465+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.589567+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.589736+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.589838+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.590013+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.590117+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.590286+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:347 +0x267
2020-12-24T13:55:52.590387+00:00 app[worker.1]: main.connectToWhatsApp()
2020-12-24T13:55:52.590554+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:325 +0x4d1
2020-12-24T13:55:52.590656+00:00 app[worker.1]: main.initializeWhatsApp()
2020-12-24T13:55:52.590830+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:312 +0xc4
2020-12-24T13:55:52.590933+00:00 app[worker.1]: main.main()
2020-12-24T13:55:52.591127+00:00 app[worker.1]: /tmp/build_847ed84c/WA2DC.go:89 +0xea
2020-12-24T13:55:52.687290+00:00 heroku[worker.1]: Process exited with status 2
2020-12-24T13:55:52.743424+00:00 heroku[worker.1]: State changed from up to crashed

```

Merry Christmas!

**Comment by FKLC** [comment]
Hey Seffs, I updated the bot. It shouldn't crash anymore. In your case as far as I understand it was caused by a video file bigger than 8MB. However, I don't know what causes this line: `2020-12-24T13:55:52.568543+00:00 app[worker.1]: panic: interface conversion: interface {} is nil, not string`. Do you still get that error or not?

**Comment by seffs** [comment]
I don't. The bot restarts itself and everything works as expected. I will report back if I encounter more errors. Thanks for the quick patch
