### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by heryoff** [FKLC/WhatsAppToDiscord#31]
```
goroutine 3708 [running]:
log.Panicln(0xc0000b9e00, 0x1, 0x1)
        log/log.go:365 +0xb7
main.handlePanic(...)
        command-line-arguments/WA2DC.go:730
main.waSendMessage(0xc000251240, 0x1b, 0xc000006120)
        command-line-arguments/WA2DC.go:418 +0x34a
main.dcOnMessageCreate(0xc0000d6b40, 0xc000006120)
        command-line-arguments/WA2DC.go:230 +0x191
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xcae8b8, 0xc0000d6b40, 0xc04400, 0xc000006120)
        github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x52
created by github.com/bwmarrin/discordgo.(*Session).handle
        github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x118
Bot is now running. Press CTRL-C to exit.
panic: sending message timed out


goroutine 2230 [running]:
log.Panicln(0xc000125e00, 0x1, 0x1)
        log/log.go:365 +0xb7
main.handlePanic(...)
        command-line-arguments/WA2DC.go:730
main.waSendMessage(0xc0000541a0, 0x1b, 0xc0000ce028)
        command-line-arguments/WA2DC.go:418 +0x34a
main.dcOnMessageCreate(0xc0000dab40, 0xc0000ce028)
        command-line-arguments/WA2DC.go:230 +0x191
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xcae8b8, 0xc0000dab40, 0xc04400, 0xc0000ce028)
        github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x52
created by github.com/bwmarrin/discordgo.(*Session).handle
        github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x118
Bot is now running. Press CTRL-C to exit.

```
Don't really know what this is but it makes the script crash. Hopefully you can figure it out

**Comment by FKLC** [comment]
The latest release should fix this issue. If you run into another bug feel free to open a new issue.
