### ISSUE TITLE
Crashes & Delete chat problem

### ISSUE THREAD

**Issue by heryoff** [FKLC/WhatsAppToDiscord#32]
```goroutine 870 [running]:
log.Panicln(0xc0000c3c88, 0x1, 0x1)
        log/log.go:365 +0xb7
main.handlePanic(...)
        command-line-arguments/WA2DC.go:735
main.getOrCreateChannel(0x9d0635, 0xf, 0x0)
        command-line-arguments/WA2DC.go:617 +0x1e5
main.dcCommandStart(0xc0001dac30, 0x3, 0x3)
        command-line-arguments/WA2DC.go:251 +0x35d
main.dcOnMessageCreate(0xc0000dab40, 0xc0003000f0)
        command-line-arguments/WA2DC.go:212 +0x372
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x9ee8f8, 0xc0000dab40, 0x944400, 0xc0003000f0)
        github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x52
created by github.com/bwmarrin/discordgo.(*Session).handle
        github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x118
Bot is now running. Press CTRL-C to exit.
```
1) Still crashing giving this error
2) Is there a way to fix the fact that it deletes all my chats whenever it crashes?

**Comment by FKLC** [comment]
The latest release should fix this issue. If you run into another bug feel free to open a new issue.
